buildVariable: true
category:
- SERIF
familyName: Noto Serif Myanmar
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSerifMyanmar.glyphs
